spring.application.name=BookShopApp
spring.datasource.url=jdbc:mysql://localhost:/bookshop
spring.datasource.username=root
spring.datasource.password=zz123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 


